### ISSUE TITLE
RPi testing

### ISSUE THREAD

**Issue by mv4wd** [wherget/ddx3216http#2]
Hi, I've installed the node application on a RPi3 with the latest Raspbian.
I've managed to make it work but I've found some issues. 
First was the index of the midi output port, I had to change from 0 to 1 in the lines

console.log("Sending on midi out", output.getPortName(1));
output.openPort(1);

I don't know if this issues is specific to RPi.

Then I had a parsing error in ALSA send for the two calls ping and requestMeterData. They both call assembleCommand that is later called also inside sendCommand, so this causes issues. 
Also this two sysex seem to have no effect (no answer from the mixer). Is a sysex protocol document available for the DDX3216?

**Comment by wherget** [comment]
Hi!
Sorry for the long wait. As you may have noticed, I haven't touched this project in quite a while, so forgive me if my memory is a bit rusty.

The change in output port seems very plausible, this is dependent on your MIDI USB adapter. You are right in that it is a bit unfortunate to be hard-coded to what I have available. This should probably be solved with a config file, environment variable or startup parameter. 

I'll try and find the last version I had on a device, there may be fixes that haven't landed in the repository yet. I definitely had it working at some point, so you shouldn't be experiencing ALSA issues (barring upstream dependency fixes of course, which I didn't check).

There is, of course, a Sysex protocol document, which I implemented the commands in this program from. It is unfortunately still copyrighted by Behringer, so I cannot include it in the repository. They will send it to you if you ask their support nicely though.

**Comment by mv4wd** [comment]
I've contacted Behringer (now music tribe) support. Unfortunately they've only been able to provide the two MIDI maps tables available in the DDX manual. The sysex manual seems to be not available anymore. They've been very rapid and polite.

**Comment by wherget** [comment]
Strange. I received my copy in 2014 from MUSIC Group Research UK Limited, who seem to be still in business. Maybe you could try getting hold of them directly. The document is titled "Sysex Documentation Version 1.0 September 2002". The filename I have (245249.pdf) didn't yield any obvious results when googling, but maybe mentioning it to them helps? (I consider the filename and title not part of the document, which states in really obvious terms I'm not supposed to share it. Verbatim, I guess.)

**Comment by mv4wd** [comment]
Got 2nd answer after mentioning the PDF, device is too old and no more resources are available.
I've found more sysex examples i project https://github.com/stereokrauts/stereoscope

**Comment by wherget** [comment]
Well, hang on, the copyright remark says it could be shared with express written permission. If they don't provide it themselves anymore, maybe they don't care about publishing either. Do you have a ticket reference I can cite to ask them for permission?

**Comment by mv4wd** [comment]
yes Support Request (Case: 01040241) [ ref:_00D2818RET._5000I1oqY2k:ref ]
Thanks for your effort

**Comment by wherget** [comment]
Sorry, I can't seem to submit a ticket through their Care Portal (the spinner after submit never goes away). Their new support platform is real garbage. So currently I think you can ask them whether they would release the document, or if you have other ways to reach support (maybe an email address?) I'd be happy to try that.

**Comment by mv4wd** [comment]
I've tried to explain my best to the support team, they've been very active. This is the answer:

Dear Marco,
 
Thank you very much for your reply.

Unfortunately, you have contacted the technical support team. We do not deal with these matters, but all of our old documents are free to be released publicly.

**Comment by mv4wd** [comment]
Could you add the manual in the repository?

**Comment by wherget** [comment]
I don't feel super comfortable yet with just that half-sentence to go on. I've been trying to get ahold of Music Tribe Legal, without much success so far. (Probably a combination of Christmas and impending Chinese new year.) I'll let you know how things develop.

**Comment by mv4wd** [comment]
I've received today a mail from Music Tribe stating that their CRM has been updated and some issues status were lost. They're asking again if my request can be marked as closed.  The new/old numbering of my request is CAS-29208-Q7L1N4 CRM:0233142 Try to mention that.

**Comment by wherget** [comment]
Now available in [develop branch, doc folder](https://github.com/wherget/ddx3216http/tree/develop/doc) and [on archive.org](https://archive.org/details/245249-ddx-3216-sysex-documentation-1.0) 
I figure 20 Years is enough to be confident no commerial interests are being violated.

**Comment by mv4wd** [comment]
Thanks, I'm still using my DDX and the info might be very useful to make a personal monitor control interface for the band.
