### ISSUE TITLE
Incomplete message?

### ISSUE THREAD

**Issue by Plexoplasma** [wherget/ddx3216http#4]
Hi, first of all... thank you!
A remote controll is all the Desk is lacking.

But my problem is: (im pretty new to Linux)

I got the server running i think. I can open the Browser and see the faders and all.
Also when i either use the Desk or the Browser i can see my MIDI controller gets or sends something.

But nothing happens, either the Browser side changes or the Desk.

when i start the server it says:

up to date, audited 92 packages in 854ms

12 packages are looking for funding
    run `npm fund` for details

found 0 vulnerabilities
Sending on midi out ESI MIDIMATE Ex:ESI MIDIMATE eX MIDI 2 24:1
Receiving on midi in ESI MIDIMATE Ex:ESI MIDIMATE eX MIDI 1 24:0

MidiOutAlsa::sendMessage: incomplete message!

MidiOutAlsa::sendMessage: incomplete message!

listening on *:9080

tried different Midi Ports but nothing happens.
Got any tip for me?

**Comment by wherget** [comment]
Sorry, I don’t currently have the devices handy to reproduce the issue. As I’m inferring from your subject you too are thinking the “incomplete message” errors have something to do with it. It might be the case that some api changed over the last 9 years. 😄

The two messages are from when the tool is initially trying to read the desk.

you can run the tool with `DEBUG='*' node main` to see more verbose output. (This sets the DEBUG variable for only the command immediately after.)

I also recall the settings on the desk being a bit finicky about what needs to be enabled in the MIDI panel. I’ll give it a check when I get back to my desk which will probably be next Wednesday. I’ll keep you posted.

**Comment by Plexoplasma** [comment]
it sends me:

express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/home/plexoplasma/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  socket.io:server initializing namespace / +0ms
  socket.io:server creating engine.io instance with opts {"cleanupEmptyChildNamespaces":false,"path":"/socket.io"} +0ms
  socket.io:server attaching client serving req handler +1ms
Sending on midi out ESI MIDIMATE eX:ESI MIDIMATE eX MIDI 1 24:0
Receiving on midi in ESI MIDIMATE eX:ESI MIDIMATE eX MIDI 2 24:1
  express:router use '/' query +48ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' serveStatic +0ms
  express:router:layer new '/' +0ms
  behringer Sending SysEx: [
  'f0', '0',  '20', '32',
  '60', 'b',  'f0', '0',
  '20', '32', '60', 'b',
  '40', 'f7', 'f7'
] +1ms

MidiOutAlsa::sendMessage: incomplete message!

  behringer Sending SysEx: [
  'f0', '0',  '20', '32',
  '60', 'b',  'f0', '0',
  '20', '32', '60', 'b',
  '4f', 'f7', 'f7'
] +1ms

MidiOutAlsa::sendMessage: incomplete message!

listening on *:9080

**Comment by Plexoplasma** [comment]
and i can see both: working input and output

**Comment by wherget** [comment]
I've found the cause of the `MidiOutAlsa::sendMessage: incomplete message!` warning. I was accidentally wrapping the two initial messages with SYSEX bytes twice. RtMidi validates if a SYSEX packet is well-formed, which these were obviously not. That's fixed in 0.4.1 now.

I don't *think* that should have made a difference to it not working though, as these initial messages aren't really necessary.

So I think it comes down to getting the desk set up correctly. Can you make sure you have the "DIRECT PAR. EXCL" Rx and Tx Checkmarks set in the MIDI "Rx/Tx" setup page? You can also try to change the "Receive Channel" setting on the MIDI "Setup" page. Try "OMNI"?

**Comment by Plexoplasma** [comment]
yeah i tried all MIDI settings in the Desk now. they just dont communicate.

**Comment by Plexoplasma** [comment]
also tried the omni input setting

**Comment by Plexoplasma** [comment]
ok. so i now i can change the fader values with the brwoser but i dont recieve the fader values (i dont see changes i do on the Desk. The thing i had to change was in the Desk setup under "Files" i had to set the "exchange" setting to Midi :D.
Maybe i can get the receive info to work too.

**Comment by wherget** [comment]
I would never have thought that Files would have anything to do with it, but good to know, thank you very much for your investigative work. I might have just enabled that setting when I got my desk to do something related to the firmware upgrade and never thought about it ever again. 😆 Makes sense though, since File Transfers are done over SYSEX as well.

Also, now you've made me unsure whether this even ever worked at all bidirectionally. I might have just used it to control the AUXes one-way from the web. 🤔 Should just be a packet decoding thing though. Anyway, I dug up my Pi (which thankfully had no changes on top of 0.3.0) and Midi interface, so I'll be doing some sleuthing of my own come Wednesday evening.

**Comment by Plexoplasma** [comment]
Thank you for ur work mate. It's gonna help a lot being on my own on line check!

**Comment by wherget** [comment]
Yeah, that was one of the main use cases I was thinking about too. The other, giving my bandmates the option to adjust their moitor mix themselves. Anyway, here's what came out of the trial...

Bidirectional sync does in fact work, sorta. Fader changes from the desk are received and stored. Just the web client doesn't update when you change something from the desk. You need to reload the page to see fader changes. I don't think pushing updates to the web client is hard to add, but requires adding an event system to the MIDI component. Also I haven't really found a way to tell the desk to send me the current state without changing anything. Although now that I think about it, it might get sent on bootup. I'll check next time. For now, wiggle fader first, then hit refresh. Also, running with `DEBUG=behringer` should give you messages when fader changes are received.

I've some changes queued up I did today to allow you to set the desk address, in case some mad soul wants to try and control multiple desks with this, that also adds some more debug output which might be helpful for you. I'll try to clean it up in the coming days. Once that's up, I'll probably need you to do a round of posting logs again.

My desk had the following:
```
MIDI Setup:
Source  Rate       Transmit Ch   Receive Ch  MMC Dev
[ MTC ] [ 25 FRM ] [    11    ] [   OMNI   ] [   00   ]
```
In addition to the Rx/Tx setup I described in https://github.com/wherget/ddx3216http/issues/1#issuecomment-396917500

In the meantime, just to be safe, you do have the ports plugged the right way round, i.e. "1" of the Midimate into MIDI **In** of the desk and "2" into MIDI **Out**?

**Comment by Plexoplasma** [comment]
Yeah. The ports are definitely right because i marked them so I don't need to look for those tiny numbers on them 😅. It's no need for me to see changes made by the desk I just thought it's not working for me. With the debug command I see all changes from web and the desk. I set the import channel to Omni that's working for me and sending channel makes no difference because (idk why) but they all work. It's already working pretty well for my situation! But I will ofc send logs again once ur done with the update. Thanks mate!

**Comment by wherget** [comment]
I've pushed 0.5.0 which should do bidirectional sync. Please give it a go and see if it works for you.

Receive/Transmit channel not making a difference is expected, if anyone ever wants to control multiple desks I'll think about changing that.

Thanks again for the hint about "File Exchange via" (that's now in the README, too). I'd never thought that may be relevant, great find.

If you think this is working (as fas as it's implemented) for you now, please close this issue. Feel free to open a new one if you find another issue or would like to petition a new feature.

**Comment by Plexoplasma** [comment]
Yeah, it's working perfectly now. Thank you very much!
